config.h: rename to sleepd_config.h to make sure the right one is included
* fails with json-c-0.14, because of how include paths are orderred it
  includes the one from recipe-sysroot/usr/include/json-c/config.h

/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-gcc -DPMLOG_TRACES_ENABLED -DPMLOG_TRACE_COMPONENT=\"sleepd\" -DWITHOUT_RTC_WATCHDOG -IConfigured/src -I/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0/recipe-sysroot/usr/include/libxml2 -I/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0/recipe-sysroot/usr/include/json-c -I/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0/git/include/internal -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0=/usr/src/debug/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0                      -fdebug-prefix-map=/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0=/usr/src/debug/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0                      -fdebug-prefix-map=/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0/recipe-sysroot=                      -fdebug-prefix-map=/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0/recipe-sysroot-native=   -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0/recipe-sysroot -DUSE_PMLOG_DECLARATION -DREBOOT_TAKES_REASON -Wall -Werror=implicit-function-declaration --std=gnu99 -Wl,--no-undefined -DNDEBUG -MD -MT CMakeFiles/sleepd.dir/src/utils/init.c.o -MF CMakeFiles/sleepd.dir/src/utils/init.c.o.d -o CMakeFiles/sleepd.dir/src/utils/init.c.o   -c /OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0/git/src/utils/init.c
/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0/git/src/utils/init.c: In function 'TheOneInit':
/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0/git/src/utils/init.c:155:9: error: 'gSleepConfig' undeclared (first use in this function); did you mean 'GSliceConfig'?
  155 |     if (gSleepConfig.debug)
      |         ^~~~~~~~~~~~
      |         GSliceConfig
/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/sleepd/2.0.0-1+gitAUTOINC+805f724dd3-r0/git/src/utils/init.c:155:9: note: each undeclared identifier is reported only once for each function it appears in

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Change-Id: Ib281248fee1e91347fb15da8c59822439ada8179